INSERT INTO products (name, category, base_prce, stock) VALUES
("Classic Hamburger",    "BRGR",  5.00, 50),
("Custom Hamburger",     "BRGR",  5.00, 50),
("Classic Sandwich",     "SAND",  4.00, 50),
("Custom Sandwich",      "SAND",  4.00, 50),
("Classic Wiener",       "WNER",  3.50, 50),
("Custom Wiener",        "WNER",  3.50, 50),
("Garlic Bread",         "SIDE", 12.00, 50),
("French Fries",         "SIDE",  9.90, 50),
("Onion Rings",          "SIDE", 10.00, 50),
("Nuggets",              "SIDE", 11.00, 50),
("Mozzarella Sticks",    "SIDE", 12.90, 50),
("Soda 350ml",           "BEVG",  5.00, 50),
("Soda 500ml",           "BEVG",  7.00, 50),
("Natural Juice",       "BEVG",   8.50, 80),
("Drink",                "BEVG", 12.50, 50),
("Chocolate Brownie",    "DSRT", 12.50, 30),
("Chocolate Cookie",     "DSRT",  5.00, 30),
("Ice Cream Cup",        "DSRT",  3.50, 50),
("Custom Ice Cream",     "DSRT",  6.50, 50),
("Hamburger Combo",      "CMBO",  0.00, 30),
("Sandwich Combo",       "CMBO",  0.00, 30),
("Wiener Combo",         "CMBO",  0.00, 30),
("Serving Combo",        "CMBO",  0.00, 35),
("Kids Combo",           "CMBO",  0.00, 30);

INSERT INTO ingredients (name, category, price) VALUES ();
-- Bun
("Potato",               "BBRG",  2.50),
("Pretzel",              "BBRG",  3.00),
("Wheat",                "BBRG",  2.75),
("Baguette",             "BSND",  3.00),
("Ciabatta",             "BSND",  2.90),
("Panini",               "BSND",  3.10),
("Bakery",               "BWNE",  2.00),
("Brioche",              "BWNE",  2.50),
("French",               "BWNE",  2.75),
-- Patty
("Beef Patty",           "PTTY",  8.00),
("Chicken Patty",        "PTTY",  6.50),
("Porky Patty",          "PTTY",  7.00),
("Veggie Patty",         "PTTY",  9.00),
-- Meat
("Chicken Breast",       "MEAT",  6.00),
("Turkey Breast",        "MEAT",  6.50),
("Roast Beef",           "MEAT",  8.60),
("Tofu",                 "MEAT",  9.00),
-- Sausage
("Chicken Sausage",      "SAUS",  5.00),
("Pork Sausage",         "SAUS",  5.75),
("Veggie Sausage",       "SAUS",  7.89),
("Vienna Sausage",       "SAUS",  6.00),
-- Double Meats
("Double Meat",          "DSND",  7.52),
("Double Patty",         "DBRG",  7.62),
("Double Sausage",       "DWNE",  6.32),
-- Salad
("Arugula",              "SALD",  0.50),
("Bell Peppers",         "SALD",  0.50),
("Corn",                 "SALD",  1.00),
("Diced Onion",          "SALD",  0.50),
("Jalapeños",            "SALD",  1.00),
("Lettuce",              "SALD",  0.50),
("Sliced Tomato",        "SALD",  0.50),
("Black Olives",         "SALD",  2.00),
("Green Olives",         "SALD",  1.00),
("Red Onion",            "SALD",  0.50),
("Peas",                 "SALD",  1.00),
("Pickle",               "SALD",  1.50),
-- Common Extras
("Bacon",                "XTRA",  2.00),
("Egg",                  "XTRA",  1.50),
("Salami",               "XTRA",  1.89),
-- Categorized Extras
("Caramelized Onions",   "XBRG",  2.50),
("Sautéed Mushrooms",    "XBRG",  3.50),
("Potato Sticks",        "XWNE",  1.50),
("Bacon Bits",           "XWNE",  2.50),
("Sun-Dried Tomato",     "XSND",  3.00),
("Sliced Ham",           "XSND",  4.99),
("Sliced Mortadella",    "XSND",  4.79),
-- Side Extras
("French Fries",         "XSID",  9.90), 
("Garlic Bread",         "XSID",  6.99), 
("Grated Parmesan",      "XSID",  2.79), 
("Mozzarella Sticks",    "XSID", 12.90), 
("Nuggets",              "XSID", 11.99), 
("Onion Rings",          "XSID", 10.75), 
-- Cheese
("American",             "CHSE",  2.50),
("Cheddar",              "CHSE",  2.50),
("Gorgonzola",           "CHSE",  4.00),
("Monterey Jack",        "CHSE",  4.00),
("Mozzarella",           "CHSE",  2.50),
("Parmesan",             "CHSE",  4.00), 
("Pepper Jack",          "CHSE",  4.00),
("Provolone",            "CHSE",  2.50),
("Swiss",                "CHSE",  2.50),
("Cream",                "CHSE",  2.50),
-- Dessert Extras
("Chocolate Syrup",      "XDES",  2.00),
("Strawberry Syrup",     "XDES",  2.00),
("Whipped Cream",        "XDES",  3.00),
("Chocolate Chips",      "XDES",  2.50),
-- Sauce
("Cheddar Sauce",        "SAUC",  2.15),
("Garlic Sauce",         "SAUC",  1.79),
("Green Sauce",          "SAUC",  1.79),
("Ketchup",              "SAUC",  0.10),
("Mayonnaise",           "SAUC",  0.10),
("Mustard",              "SAUC",  0.10),
("Spicy Saude",          "SAUC",  0.50),
-- Beverage Extras
("Ice Cubes",            "XBEV",  0.00),
("Lemon Slice",          "XBEV",  0.50),
("Mint Leaves",          "XBEV",  0.50),
("Vanilla Flavor Syrup", "XBEV",  2.00),
("Caramel Flavor Syrup", "XBEV",  2.00),